# Generated by Django 3.2.5 on 2021-07-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textdata',
            old_name='text02',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='textdata',
            old_name='text01',
            new_name='text',
        ),
    ]
