# Generated by Django 3.2.5 on 2021-07-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210710_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdata',
            name='datamodel',
        ),
    ]
